name: Deploy to S3

description: Deploy to S3

inputs:
  aws-access-key-id:
    required: true
    description: AWS Access Key
  aws-secret-access-key:
    required: true
    description: AWS SECRET KEY
  aws-region:
    required: true
    description: AWS Region
  s3-bucket:
    required: true
    description: S3 Bucket
  build-path:
    required: true
    description: Project build folder
  distribution-id:
    required: false
    description: Cloudfront distribution id

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy to S3 bucket
      run: |
        aws s3 sync ${{ inputs.build-path }}/ s3://${{ inputs.s3-bucket }} --delete
      shell: bash

    - name: Invalidate Cloudfront
      if: ${{ inputs.distribution-id != '' }}
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution-id }} --paths "/*"
      shell: bash
